# Link: https://medium.com/@ikbenezer/automate-your-laravel-app-deployment-with-github-actions-ab7b2f7417f2

name: Deploy Laravel Project on Stagging Server

on:
  push:
    branches:
      - stage

# Authenticate to the the server via ssh
# and run our deployment script
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to STAGE server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGE_SSH_HOST }}
          username: ${{ secrets.STAGE_SSH_USER }}
          port: ${{ secrets.STAGE_SSH_PORT }}
          key: ${{ secrets.STAGE_SSH_PRIVATE_KEY }}
          script: "cd /var/www/corrbuilder && /var/www/corrbuilder/stage_deploy.sh"
